language: rust
rust:
  - 1.13.0
  - 1.16.0
  - stable
  - beta
  - nightly
script: >
  cargo build $CARGO_FLAGS --features "$CARGO_FEATURES"
  && cargo test $CARGO_FLAGS --features "$CARGO_FEATURES"
env:
  - >
    CARGO_FLAGS="--verbose --no-default-features"
    CARGO_FEATURES=
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      env: CARGO_FEATURES=nightly
