[package]
name = "build-helper"
version = "0.1.0"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

[features]
default = []
nightly = []

[workspace]
members = [
    "tests/pkgs/basic",
    "tests/pkgs/basic-nightly",
]

[dependencies]
semver = "0.6.0"
